---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
    tag: latest

inputs:
- name: java-buildpack
- name: java-buildpack-system-test
- name: bbl-state
- name: built-buildpack

run:
  path: java-buildpack/ci/tasks/system-tests/run.sh

params:
  SYSTEM_DOMAIN:
